### ISSUE TITLE
Create docker container for docker hub auto builds

### ISSUE THREAD

**Issue by oliv3r** [curl/curl-docker#1]
See curl/curl#3714

**Comment by oliv3r** [comment]
@xquery what do you think?

**Comment by xquery** [comment]
this work is starting to emerge on my fork

   https://github.com/xquery/curl-docker

any advice, observation, comment would be gladly received.

note- different arch (and platforms) should show up in a bit

**Comment by xquery** [comment]
we originally planned to use travis and push to docker hub ... which is a familiar idiom for the rest of ppl working on curl - FWIW I do not have any pros/cons using docker hub auto builds

**Comment by xquery** [comment]
we may revisit this in the future, for now closing
