### ISSUE TITLE
[FEATURE REQUEST] Allow to save files

### ISSUE THREAD

**Issue by silvioprog** [curl/curl-docker#12]
Hi.

Since `curl` is commonly used for downloading files, it would be nice to allow something like this:

```
docker run --rm curlimages/curl:lastest <host>/some-file.txt --output some-file.txt
```

so, the above command would be equivalent as:

```
curl <host>/some-file.txt --output some-file.txt
```

however, if you try this in the current curl-docker, it raises the following error:

```
➜  ~ docker run --rm curlimages/curl:7.67.0 https://www.google.com/humans.txt --output humans.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file humans.txt: Permission denied
100   286  100   286    0     0    561      0 --:--:-- --:--:-- --:--:--   562
curl: (23) Failed writing body (0 != 286)
```

regards,

**Comment by xquery** [comment]
thx for taking the time to raise an issue.

as an alternate approach, have you tried pipe redirection to save file from the docker run command ?

for example:

```
> docker run --rm curlimages/curl:7.67.0 https://www.google.com/humans.txt > humans.txt
```
would save a file to humans.txt onto the docker host.

otherwise you are attempting to save a file into the container itself eg. try ~/humans.txt which would save file to user directory (which you should have perms for) ... you would then need to use docker cp to copy that file from the container to the host machine.

**Comment by dfandrich** [comment]
The other way would be to map an outside directory into the container and write
the file there, like this:

docker run -v /tmp:/tmp curlimages/curl:7.67.0 https://www.google.com/humans.txt --output /tmp/humans.txt

**Comment by silvioprog** [comment]
@xquery thanks for the feedback! :-)

Hmm, I never used `>` to save (big) files from curl. Maybe using `VOLUME`s could be better as suggested by @dfandrich .

If you want, I'm ready to send a PR allowing to use `VOLUME`s. :-)

**Comment by xquery** [comment]
unless I am missing something - I do not believe any additional work is required for using volumes as per @dfandrich example.

```
docker run -v /tmp:/tmp curlimages/curl:7.67.0 https://www.google.com/humans.txt --output /tmp/humans.txt
```
This nicely illustrates how curl downloads file which should exist in the host machine's /tmp directory.

Considering you have several options that work today I am going to close this issue.

**Comment by lonix1** [comment]
Hi @xquery 

````
docker run -v /tmp:/tmp curlimages/curl:7.67.0 https://www.google.com/humans.txt --output /tmp/humans.txt
````

Has something changed since you posted that, since it gives me the error too. (Permission denied).

**Comment by xquery** [comment]
no ... and defo nothing has changed with 7.67.0 (previous version) ... sounds like a perms issue with your mount (try a different dir then /tmp ... which might have some expectations).

**Comment by lonix1** [comment]
@xquery Good advice, thanks!

**Comment by maaft** [comment]
Uhm, it gives me also the same error.

```
docker run -v $(pwd):/some-arbitary-mount-point -it curlimages/curl -L --output /some-arbitary-mount-point/test.tar "example.com/file.txt"
```
