### ISSUE TITLE
SFTP support?

### ISSUE THREAD

**Issue by kuroiokami** [curl/curl-docker#13]
Just downloaded the latest curl docker image from dockerhub and going into the container I don't see support for SFTP?

**Comment by xquery** [comment]
thx for the feature request.

yes, with the initial release of curlimage/curl we opted for a small subset of curl features ... we will add sftp (and enable a few other features) in next release.

**Comment by kuroiokami** [comment]
Thanks. SFTP was listed on your dockerhub page as something it supported.

**Comment by xquery** [comment]
thx, will prepare and publish new release this week

**Comment by xquery** [comment]
latest docker images have been updated

**Comment by ciarancoffey** [comment]
Seems like sftp was disabled again.
```curl: (1) Protocol "sftp" not supported or disabled in libcurl```
```FROM curlimages/curl:7.83.1```
