### ISSUE TITLE
Multi-arch build

### ISSUE THREAD

**Issue by l31g** [curl/curl-docker#17]
Hi, is there a plan to create multi-arch images to add arm64 and armhf architectures?

**Comment by xquery** [comment]
I have considered refactoring existing build to generate multi-arch images but no explicit roadmap - I think this is a good feature request.

**Comment by l31g** [comment]
Thanks for the reply! Should I file this different or the "enhancement" label is enough?

**Comment by xquery** [comment]
this is good enough - I will (eventually) raise a PR addressing this ... that PR will have more information and you should be notified (if you want to help test it).

**Comment by joakimr-axis** [comment]
As a curl user, such a multiarch container is absolutely what I need/expect. Earlier today, I built such a multiarch thingy that gives me the user experience I reckon is what one wants:

https://hub.docker.com/repository/docker/d97jro/curl

So, it supports amd64, arm32v7 and aarch64.

But then there is of course the question on how to build the containers in the multiarch manifest. In my case, I built them on three separate machines of each architecture, which is of course the easy option when it comes to creating the Dockerfile. Then again, on would perhaps create them by cross-compiling, making it buildable for all targets regardless of what hosts are available.

Another option, which is easier but might bring a less sophisticated end result, is to use e.g. a Debian image and use apt to install the packages for the desired target architecture in a special directory which is then copied to a scratch container in the final step. Such a solution would also enable any host to build for all targets.

What would be your thoughts on this?

**Comment by l31g** [comment]
I have worked on multi-arch automatic build scripts. I've used Docker Buildx. I have used a container with Buildx and QEMU to build multi arch images using Gitlab's CI. Here's the file: https://gitlab.com/arm-research/smarter/edgefaas/edgefaas-manager/-/blob/master/.gitlab-ci.yml.

**Comment by joakimr-axis** [comment]
> I have worked on multi-arch automatic build scripts. I've used Docker Buildx. I have used a container with Buildx and QEMU to build multi arch images using Gitlab's CI. Here's the file: https://gitlab.com/arm-research/smarter/edgefaas/edgefaas-manager/-/blob/master/.gitlab-ci.yml.

I have not used buildx or Gitlab's CI, so I could not give any insightful comments on that file myself, but if the result is a nice multiarch curl image I am a happy camper! :)

**Comment by l31g** [comment]
The Docker commands could be reused to create the multi-arch images.
________________________________

**Comment by xquery** [comment]
working on this now - will synthesize all the good advice and come up with a PR soon

**Comment by joakimr-axis** [comment]
> working on this now - will synthesize all the good advice and come up with a PR soon

Very nice, and appreciated!

**Comment by xUnholy** [comment]
I've just come across this image which I need to run on ARM64, I was about to update this myself and compile using `buildx` in my community where this seems to be a reoccurring theme: https://github.com/raspbernetes/multi-arch-images

**Comment by xUnholy** [comment]
@xquery I'm not sure how long you might take to prepare your PR, I can create one with github actions if you don't mind unless you want it to be in travisci still?

**Comment by xUnholy** [comment]
https://github.com/raspbernetes/multi-arch-images/pull/76 Maintaining the image for ARM/ARM64/AMD64 here - happy to propose it back upstream.

**Comment by xquery** [comment]
thx for the offer will take a look, though we are using buildx as well ... we have a test and will be releasing today/tmrw at some point
