### ISSUE TITLE
Duplicate line in Dockerfile

### ISSUE THREAD

**Issue by patrickhuber** [curl/curl-docker#21]
Looks like commit a9663b8dd8dee6ae468e9d242375fc24e7ad6440 duplicated the following line:

```
COPY --from=builder "/alpine/usr/local/lib/libcurl.so" "/usr/lib/libcurl.so"
```

https://github.com/curl/curl-docker/blob/4ef386bc5fe16a3b52c7691cb4f8b48f2a77397a/alpine/latest/Dockerfile#L90

**Comment by xquery** [comment]
nice catch will address

J

**Comment by xquery** [comment]
will include fix in next release

**Comment by xquery** [comment]
this will get included in next release to docker hub
