### ISSUE TITLE
Contribute to the library

### ISSUE THREAD

**Issue by J0WI** [curl/curl-docker#23]
It would be great if you could do the steps to get into Dockers standard library aka "Official Images".

There are some administrative steps to fulfill:
https://github.com/docker-library/official-images#contributing-to-the-standard-library

This will enhance maintenance, trust and visibility of this Docker image. Images in the library are also rebuilt against new base image releases and it supports multiarch builds.

**Comment by bagder** [comment]
I'd be supportive of such a move. @xquery, you think can we convert that into some action items to work on? What's needed to get done?

**Comment by xquery** [comment]
I am in agreement though I would like to understand motivation, pros and cons before we start anything.

**Comment by J0WI** [comment]
The cons are the administrative steps, the [review process](https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md) (needs some patience) and you may have to adjust your Dockerfile to meet the best practices of the library or to integrate their toolchain. I can submit PRs for them.
Pros are automation, [multi arch support](https://github.com/docker-library/official-images#multiple-architectures) and the "official image" stamp.
Once the image is accepted, maintenance tends to become easier.

**Comment by bagder** [comment]
Is the review process going to be an issue if this is going to be updated an average of once every 56 days?

**Comment by J0WI** [comment]
For release upgrades? No.

**Comment by xquery** [comment]
the registry landscape has changed quite a bit over the past few years ... closing this as we may have other options available (eg release to multiple registries, etc)
