### ISSUE TITLE
which ssl backend and how to keep ca updated

### ISSUE THREAD

**Issue by xquery** [curl/curl-docker#3]

**Comment by jay** [comment]
The OpenSSL backend has a disproportionately large user base so that's what I would use. The ca I would use curl's [lib/mk-ca-bundle.pl](https://github.com/curl/curl/blob/curl-7_64_1/lib/mk-ca-bundle.pl) and if possible find some way to automate adding it to the image.

**Comment by xquery** [comment]
On Thu, 2 May 2019 at 21:33, Jay Satiro <notifications@github.com> wrote:

> The OpenSSL backend has a disproportionately large user base so that's
> what I would use. The ca I would use curl's lib/mk-ca-bundle.pl
> <https://github.com/curl/curl/blob/curl-7_64_1/lib/mk-ca-bundle.pl> and
> if possible find some way to automate adding it to the image.
>

good point - as suggested previously - going to use the good idea of using
the survey to drive what options are enabled and auditing the various
platforms enabled features/build options to see how to 'thread the
needle(s)' .

I also wondered about the idea of a dynamic docker build eg. click these
options and build a custom docker image ... thats obviously off topic and a
distraction but maybe something I will do as an adjunct shell script.

still working ...

Jim

**Comment by xquery** [comment]
with alpine it seemed simple enough to use 

```
apk add --no-cache ca-certificates
```
as proposed by the fix #6
