### ISSUE TITLE
Update libcurl

### ISSUE THREAD

**Issue by rusikf** [curl/curl-docker#40]
Hi curl hackers, for http3 support we need to update libcurl library, is it possible ? ( I tested on ubuntu 18.04 + your curl-docker )
@xquery @bagder @ducksecops 
`docker run --rm curlimages/curl:7.71.1 --http3 https://www.cloudflare.com/ -I`
curl: option --http3: the installed libcurl version doesn't support this
curl: try 'curl --help' or 'curl --manual' for more information

Looks, like pass env doesnt work `docker run -e LD_LIBRARY_PATH='/usr/lib/x86_64-linux-gnu/libcurl.so.4.5.0' --rm curlimages/curl:7.71.1 --http3 https://www.cloudflare.com/ -I
`

**Comment by xquery** [comment]
at the moment, http3 is experimentally supported in curl ... though it would be easy enough to make the curl docker build that in ... perhaps a separate image for experimental support ? unsure what the right answer should be.

**Comment by rusikf** [comment]
Ok, if somebody helps , I installed curl from source for it
https://github.com/rusikf/setup-curl-for-http3

**Comment by xquery** [comment]
Building curl with http3 feature enabled is not a problem (using either ngtcp3 or quiche backends) ... this is a 'should we include http3 experimental support in the official curl docker image' type of question ... I am leaning towards not adding support for any experimental features to standard curl docker image.

**Comment by rusikf** [comment]
Ok thanks for explaining that :)
