### ISSUE TITLE
Sending local file with curl / ftp

### ISSUE THREAD

**Issue by sinsedrix** [curl/curl-docker#41]
I tried upload a local file to my ftp server using this command:

> docker run --rm curlimages/curl --T test.txt ftp://ftp_user:ftp_passwd@1.2.3.4

I get the following error:

> curl: Can't open 'test.txt'!

Of course, if I just write the command with curl, it's ok:

> curl --T test.txt ftp://ftp_user:ftp_passwd@1.2.3.4

I suppose it can't work because test.txt is not in the container.
With other containers, I'm used to specify a `-v "$PWD:/workdirectory"` option, but I dont' know if it's available in this container.

Am I missing an option or a work directory to use local files?

Thanks.

**Comment by xquery** [comment]
yes we could make that a bit more explicit in the documentation for uploading scenarios eg. you would need to mount volume in container as you suggested (or perhaps docker copy file into container).

Something like the following works

```
docker run --rm -it -v "$PWD:/workdirectory" curlimages/curl -d@/workdirectory/test.txt http://httpbin.org/post
```

**Comment by sinsedrix** [comment]
> 
> 
> yes we could make that a bit more explicit in the documentation for uploading scenarios eg. you would need to mount volume in container as you suggested (or perhaps docker copy file into container).
> 
> Something like the following works
> 
> ```
> docker run --rm -it -v "$PWD:/workdirectory" curlimages/curl -d@/workdirectory/test.txt http://httpbin.org/post
> ```

It doesn't seem to work:

> Warning: The file name argument 
> Warning: '-d@/work/test.tx
> Warning: t' looks like a flag.
> curl: Can't open '-d@/work/test.txt'!

Are you sure, it's not up to the image to provide/include the working directory?

Oh, it works without the `-d` prefix !

**Comment by xquery** [comment]
the example I provided works ... your error listing is confusing eg. refers to "/work/test.tx" and "/work/test.txt" ... closing this as I believe the question was answered (and no obvious issues) - if you think that is not the case continue to comment on this issue and i will re-open.
