### ISSUE TITLE
Bump to 7.74.0

### ISSUE THREAD

**Issue by J0WI** [curl/curl-docker#43]
https://curl.se/changes.html#7_74_0

**Comment by bagder** [comment]
As 7.74.0 is already on https://hub.docker.com/r/curlimages/curl I imagine @xquery mostly forgot to push the update here?

**Comment by J0WI** [comment]
I'd expect that the image is always build from the sources you're providing here.

**Comment by xquery** [comment]
yes I forgot  ... pushing and redoing travis job
