### ISSUE TITLE
research resolving problem when using alpine 3.13

### ISSUE THREAD

**Issue by xquery** [curl/curl-docker#54]
we are pinned at alpine 3.12.5 for release as we encounter some resolving issue with alpine 3.13 ... need to investigate

**Comment by J0WI** [comment]
Can you share some details or steps to reproduce?

Some pointers to related issues:
- https://github.com/alpinelinux/docker-alpine/issues/149
- https://github.com/alpinelinux/docker-alpine/issues/134#issuecomment-771430630
- https://github.com/gliderlabs/docker-alpine/issues/539#issuecomment-774615834

**Comment by skseth** [comment]
I hit this problem yesterday. Setup : Mac (Catalina) with D4M, following instructions here : https://github.com/tbreuss/local-dev, with devbox as the local domain handled by dnsmasq.

xxx$ docker run -it alpine (this is version 3.13.5)
/ # ping my.devbox
ping: bad address 'my.devbox'

xxx$ docker run -it --rm alpine:3.12.5 /bin/sh
/ # ping my.devbox
PING my.devbox (172.16.123.1): 56 data bytes
64 bytes from 172.16.123.1: seq=0 ttl=37 time=0.454 ms
64 bytes from 172.16.123.1: seq=1 ttl=37 time=0.686 ms

**Comment by xquery** [comment]
we are now at alpine 3.14.0
