### ISSUE TITLE
Curl is not updating to latest version

### ISSUE THREAD

**Issue by MohdRashid01** [curl/curl-docker#59]
Hi All,

I have curl install which is having version 7.29.0 and I want to upgrade to the latest of  v7.78.0 but issue is that i want to upgrade curl inside the docker container when i try to upgrade curl its showing the 7.29.0 version and also docker container command are using yum NOT apt. 

I try to create a new Dockerfile in that its not working while creating image its showing curl v7.29.0

**Comment by xquery** [comment]
The way to upgrade a docker image is to pull it 

> docker pull curlimages/curl:7.78.0 

or you can just use latest

> docker pull curlimages/curl:latest 

which is the best version of curl.

As for updating curl inside a container ... the approach is for any container eg. normally one would use the system's package manager or you are always free to build curl yourself.
