### ISSUE TITLE
Dns resolution problem with Alpine and Kubernetes

### ISSUE THREAD

**Issue by TLmaK0** [curl/curl-docker#65]
After version 7.77 curl is not able to resolve hosts:

`kubectl run --restart Never --image curlimages/curl:7.80.0 curl -- domain.com`
`kubectl logs curl`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: domain.com
```

`kubectl delete pod`
`kubectl run --restart Never --image curlimages/curl:7.77.0 curl -- domain.com`
`kubectl logs curl`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
100   162  100   162    0     0    295      0 --:--:-- --:--:-- --:--:--   295
```

I think this is due to problems with Alpine and Kubernetes dns reported, like this: https://www.openwall.com/lists/musl/2018/03/30/7

**Comment by xquery** [comment]
it seems like you are resolving to a 301 - to instruct curl to follow redirects you need to provide the -L option

**Comment by TLmaK0** [comment]
@xquery I think you didn't understand correctly the problem. If you look at the first request you will see a `curl: (6) Could not resolve host: domain.com` which is not correct, but if you do the same with other curl version it works as expected.

**Comment by xquery** [comment]
I think I understand your problem - what I am seeing from your initial message is a 301 ... as I do not know if your environment (or if it has changed) my assumption is things might work if you provide a -L things might work.

**Comment by TLmaK0** [comment]
Thanks  @xquery ;)

It could be realated to https://stackoverflow.com/questions/65181012/does-alpine-have-known-dns-issue-within-kubernetes

**Comment by djhoese** [comment]
It seems this was closed before the problem was identified. Are there any suggestions for what someone who wants to use these images should do when running on a Kubernetes cluster and getting these DNS "Could not resolve" errors?

**Comment by TLmaK0** [comment]
@djhoese the only way I found is to downgrade to curl 7.77
