### ISSUE TITLE
tag latest image "latest"

### ISSUE THREAD

**Issue by vx-github** [curl/curl-docker#8]
Why not tag the latest docker image with "latest"?

If it was tagged, "docker pull curlimages/curl" would work (see the suggested pull command on: https://hub.docker.com/r/curlimages/curl).

**Comment by xquery** [comment]
apologies - I had a pending set of local commits for updating to 7.66.0 release  and applied before scanning PR's.

**Comment by xquery** [comment]
initially we decided to avoid 'latest' tag

**Comment by xquery** [comment]
added 'latest' tag so the following should work now
```
docker run --rm -it curlimages/curl -v curl.haxx.se
```
