### ISSUE TITLE
Avoid using docker --squash

### ISSUE THREAD

**Issue by stain** [curl/curl-docker#9]
This is an experimental feature, so `make` fails:

    docker build --compress --squash --build-arg CURL_CONFIGURE_OPTION= --build-arg CURL_RELEASE_TAG=curl-7_66_0 --build-arg CURL_RELEASE_VERSION=7_66_0 --build-arg CURL_GIT_REPO=https://github.com/curl/curl.git --label Name=curl --label Version=1.0.0 --label se.haxx.curl=curl --label se.haxx.curl.version=7_66_0 --label se.haxx.curl.release_tag=curl-7_66_0 --label se.haxx.curl.description="network utility" -t "curl/curl:7_66_0" -f Dockerfile .

> "--squash" is only supported on a Docker daemon with experimental features enabled

See <https://docs.docker.com/engine/reference/commandline/image_build/> which requires `--experimantal true` [in the docker daemon config](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file).

Why is this experimental option needed? The build already use [multi-stage Dockerfile](https://docs.docker.com/develop/develop-images/multistage-build/) , so if the goal is to reduce the 3 layers from `COPY` perhaps it could work to replace them with:

    COPY --from=builder /alpine/usr/local/ /usr/

Or if we really do not want the other things from `/usr/local` perhaps prepare the `/usr`-to-be first within the `builder` steps as a new `/target/usr` or so - however I would think at least the curl license was required to copy over?

**Comment by xquery** [comment]
valid point - I will remove --squash and do a bit of refactoring w/ multistage

**Comment by xquery** [comment]
I have removed --squash but we now use experimental support for buildx

makefile now export DOCKER_CLI_EXPERIMENTAL=enabled

closing this for now.
